name: catalog-service CI/CD
on:
  push:
    paths:
      - 'catalog-service/**'
  pull_request:
    paths:
      - 'catalog-service/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: catalog-service
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - run: go test ./...
      - name: Build Docker image
        run: docker build -t catalog-service:ci .

  cd:
    if: github.ref == 'refs/heads/main'
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Deploy with docker compose
        run: |
          docker compose pull || true
          docker compose up -d --build
